version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lake-freeze-frontend"
s3_bucket = "deployment-zone-117819748843"
s3_prefix = "lake-freeze-frontend"
region = "us-east-1"
capabilities = "CAPABILITY_AUTO_EXPAND"
image_repositories = []
