AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
    Default: lake-freeze.kevin-mcquate.net

  DomainTLSCertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:117819748843:certificate/7d99c9a9-0cf8-4500-9c6b-31bb519c69c1

  PublicS3BucketName:
    Type: String
    Default: public-zone-117819748843-us-east-1 #!Sub public-zone-${AWS::AccountId}-${AWS::Region}
  
  PublicS3Prefix:
    Type: String
    Default: lake-freeze-frontend

Resources:
  CfDistribution:
    Type: "AWS::CloudFront::Distribution"
    Metadata:
      Comment: 'A simple CloudFront distribution with an S3 origin'
    Properties:
      DistributionConfig:
        Comment: 'A simple distribution with an S3 origin'
        Aliases:
          - !Sub ${DomainName}
        DefaultCacheBehavior:
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: !Sub 's3-origin-${PublicS3BucketName}'
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: !Sub '${PublicS3Prefix}/index.html'
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: false
        ViewerCertificate:
          AcmCertificateArn: !Ref DomainTLSCertificateArn
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        Origins:
          - DomainName: !Sub '${PublicS3BucketName}.s3.amazonaws.com'
            Id: !Sub 's3-origin-${PublicS3BucketName}'
            OriginPath: ''
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: 'PriceClass_All'




    
