
name: Deploy to CloudFront

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 117819748843
  PROJECT_PATH: lake-freeze-frontend
  DOMAIN_NAME: https://kevin-mcquate.net
  REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
  PUBLIC_ZONE_BUCKET_NAME: public-zone-117819748843-us-east-1


permissions:
  contents: read

defaults:
  run:
    working-directory: lake-freeze-frontend

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    environment: production
    container:
      image: public.ecr.aws/sam/build-nodejs18.x:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: 18
    #     cache: 'npm'
    #     cache-dependency-path: lake-freeze-frontend/package-lock.json

    - name: SAM build
      run: sam build
      
    - name: SAM deploy
      run: >
        sam deploy 
        --stack-name lake-freeze-frontend
        --region ${AWS_REGION}
        --no-fail-on-empty-changeset
        --capabilities CAPABILITY_AUTO_EXPAND
        --s3-bucket deployment-zone-${AWS_ACCOUNT_ID}
        --s3-prefix ${{ github.event.repository.name }}
        --parameter-overrides 
        DomainName=${DOMAIN_NAME}
        DomainTLSCertificateID=7d99c9a9-0cf8-4500-9c6b-31bb519c69c1
        DomainHostedZoneId=Z028090523Q7W6VMX59IC
        PublicS3BucketName=${PUBLIC_ZONE_BUCKET_NAME}


    - name: npm install
      run: npm install 

    - name: React app deploy 
      run: |
        npm run build
        aws s3 cp --recursive build/ s3://${PUBLIC_ZONE_BUCKET_NAME}/${{ github.event.repository.name }}

